### ISSUE TITLE
Kész

### ISSUE THREAD

**Issue by szviktor3** [Teaching-projects/SZE-FordProg-2020-Calculator3#1]
Szia Máté!

Elkészültem a feladattal, nézd át kérlek, hogy elfogadható-e ebben a formában.

**Comment by hegyhati** [comment]
A harmast meg tudom erre adni, de annyit mindenkepp csinalj meg vele kerlek, hogy az operator preferencia ne balrol jobbra legyen, hanem ugy ahogy "rendesen" van. (plusz 1 nemterminalis, de tudod, ott az anyagban, szoval ne hagyjuk ezt igy.)

A jegyet beirom mar most, nem tudom, hogy Te is az ebben a felevben vegzok koze tartozol-e vagy sem. Ha jobb jegyet szeretnel, akkor mondjuk a negyesert kellene egy lengyelformas tortenet, az otosert meg a valtozo deklaralasos dolog. Ezzel kicsit a mai vizsgahoz mar meg vagyunk kesve, de ha fontos lenne, akkor egyeztessunk.
